"use client";
import { ThemeProvider } from "@/components/providers/theme/theme-provider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToastProvider } from "@/providers/toast-provider";
import Navbar from "@/components/myComponents/Navbar";
import { Provider } from "react-redux";
import { store } from "@/state/store"; //persistor,
// import { PersistGate } from "redux-persist/integration/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang="en">
         <Provider store={store}>
            {/* <PersistGate loading={null} persistor={persistor}> */}
            <body className={inter.className}>
               <ToastProvider />
               <ThemeProvider
                  attribute="class"
                  defaultTheme="light"
                  enableSystem>
                  <Navbar />
                  {children}
               </ThemeProvider>
            </body>
            {/* </PersistGate> */}
         </Provider>
      </html>
   );
}
